In [34]:
import torch, sys

In [2]:
torch.__version__

'2.1.0'

In [3]:
torch.cuda.is_available()

True

In [7]:
scalar = torch.tensor([1.0])

In [11]:
scalar.shape

torch.Size([1])

In [12]:
scalar.item()

1.0

In [13]:
scalar.ndim

1

In [16]:
t = torch.tensor([1.2, 4,4.5])

In [23]:
t.numpy()

array([1.2, 4. , 4.5], dtype=float32)

In [24]:
scalar.numpy().item()

1.0

In [25]:
torch.zeros((4,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [29]:
torch.randn(2,3)

tensor([[-1.5020, -0.6779,  0.0465],
        [ 0.5788, -0.3958,  0.4767]])

In [31]:
t.dtype

torch.float32

In [32]:
torch.rand((2,3),dtype=torch.float16)

tensor([[0.1704, 0.3428, 0.4023],
        [0.5264, 0.0825, 0.2158]], dtype=torch.float16)

In [33]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
sys.getsizeof(torch.rand((10,10),dtype=torch.float32))

80

In [36]:
sys.getsizeof(torch.rand((10,10),dtype=torch.float64))

80

In [43]:
t = torch.rand((10,10),dtype=torch.float64)

In [44]:
t.nelement(), t.numel() # both => number of elements

(100, 100)

In [45]:
t.element_size()  # bytes per element of the tensor

8

In [46]:
t.device

device(type='cpu')

In [55]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [48]:
device

device(type='cuda')

In [56]:
a = torch.arange(1,4)

In [59]:
a @ a, a * a

(tensor(14), tensor([1, 4, 9]))

In [85]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [62]:
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [66]:
output.argmin(dim=1)

tensor([4, 4, 2])

In [67]:
output

tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

In [68]:
output.shape

torch.Size([3, 6])

In [69]:
output.reshape(9,2)

tensor([[2.2368, 1.2292],
        [0.4714, 0.3864],
        [0.1309, 0.9838],
        [4.4919, 2.1970],
        [0.4469, 0.5285],
        [0.3401, 2.4777],
        [6.7469, 3.1648],
        [0.4224, 0.6705],
        [0.5493, 3.9716]], grad_fn=<ViewBackward0>)

In [72]:
output.shape

torch.Size([3, 6])

In [74]:
output = output.reshape(3,6,1,1)

In [86]:
output = output.squeeze()

In [87]:
output.unsqueeze(2).shape

torch.Size([3, 6, 1])

In [88]:
output.shape

torch.Size([3, 6])

In [95]:
torch.manual_seed(seed = 20)
torch.randn(5)

tensor([-1.2061,  0.0617,  1.1632, -1.5008, -1.5944])

In [96]:
torch.manual_seed(seed = 20)
torch.randn(5)

tensor([-1.2061,  0.0617,  1.1632, -1.5008, -1.5944])

In [97]:
t

tensor([[0.9798, 0.0154, 0.1838, 0.5297, 0.0763, 0.7787, 0.2736, 0.3171, 0.0744,
         0.7901],
        [0.6036, 0.6457, 0.3691, 0.3048, 0.9585, 0.5862, 0.4004, 0.1848, 0.0111,
         0.7133],
        [0.3968, 0.2308, 0.6017, 0.2166, 0.3661, 0.1877, 0.6998, 0.0126, 0.5367,
         0.2656],
        [0.7778, 0.0149, 0.5381, 0.0342, 0.0934, 0.6352, 0.4378, 0.6075, 0.7774,
         0.7180],
        [0.5958, 0.6719, 0.8469, 0.6206, 0.3203, 0.9649, 0.9645, 0.0122, 0.2310,
         0.9666],
        [0.0872, 0.7669, 0.4253, 0.8095, 0.8696, 0.3387, 0.3715, 0.7724, 0.3457,
         0.4131],
        [0.3692, 0.5080, 0.2555, 0.9750, 0.0023, 0.6435, 0.2414, 0.9997, 0.0519,
         0.3991],
        [0.1650, 0.8788, 0.5991, 0.2238, 0.1403, 0.1774, 0.3580, 0.6203, 0.0369,
         0.1136],
        [0.0708, 0.8400, 0.8227, 0.6869, 0.1914, 0.6558, 0.4301, 0.4781, 0.2853,
         0.6679],
        [0.6025, 0.4346, 0.3952, 0.3248, 0.5566, 0.2437, 0.0018, 0.4170, 0.0664,
         0.2820]], dtype=tor

In [98]:
t.shape

torch.Size([10, 10])

In [102]:
t = t.reshape(100).type(torch.float32)

In [114]:
# Set device type
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [115]:
v = t.to('cuda')  
# v = t.to(device)

In [116]:
t.device, v.device

(device(type='cpu'), device(type='cuda', index=0))

In [123]:
torch.manual_seed(42)

In [124]:
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])